const Event = require('../models/Event');
const mongoose = require('mongoose');

/*exports.createEvent = async (req, res) => {
    try {
        const { title, description, date, startTime, endTime, location, category, price, capacity } = req.body;

        // Check if the file was uploaded by Multer
        if (!req.file) {
            return res.status(400).json({ message: "Please upload an event image." });
        }

        const newEvent = new Event({
            title,
            description,
            date,
            startTime,
            endTime,
            location,
            category,
            price: Number(price),
            capacity: Number(capacity),
            availableTickets: Number(capacity),
            // Use the filename generated by Multer
            image: `/uploads/${req.file.filename}` 
        });

        await newEvent.save();
        res.status(201).json({ success: true, event: newEvent });
    } catch (err) {
        console.error("Create Event Error:", err);
        res.status(500).json({ message: err.message });
    }
};*/
exports.createEvent = async (req, res) => {
  try {
    const {
      title,
      description,
      date,
      startTime,
      endTime,
      location,
      category,
      price,
      capacity
    } = req.body;

    // 1. Required field validation
    if (!title || !date || !location || !category) {
      return res.status(400).json({
        success: false,
        message: "Missing required fields"
      });
    }

    // 2. File validation
    if (!req.file) {
      return res.status(400).json({
        success: false,
        message: "Please upload an event image."
      });
    }

    // 3. Numeric validation
    const parsedPrice = Number(price);
    const parsedCapacity = Number(capacity);

    if (isNaN(parsedPrice) || isNaN(parsedCapacity)) {
      return res.status(400).json({
        success: false,
        message: "Invalid price or capacity"
      });
    }

    // 4. Create event
    const newEvent = new Event({
      title,
      description,
      date,
      startTime,
      endTime,
      location,
      category,
      price: parsedPrice,
      capacity: parsedCapacity,
      availableTickets: parsedCapacity,
      image: `/uploads/${req.file.filename}`
    });

    await newEvent.save();

    return res.status(201).json({
      success: true,
      message: "Event created successfully",
      event: newEvent
    });

  } catch (err) {
    console.error("Create Event Error:", err);
    return res.status(500).json({
      success: false,
      message: "Internal server error"
    });
  }
};


exports.getAllEvents = async (req, res) => {
    try {
        const events = await Event.find().sort({ createdAt: -1 });
        res.json(events);
    } catch (err) {
        res.status(500).json({ message: "Error fetching events" });
    }
};

exports.getEventById = async (req, res) => {
    try {
        const { id } = req.params;

        if (id === 'new') {
            return res.json({ 
                event: {
                    title: '', description: '', date: '', startTime: '', endTime: '',
                    location: '', category: 'Concerts', price: '', capacity: '', 
                    status: 'Upcoming'
                }, 
                analytics: { ticketsBooked: 0, revenue: 0 } 
            });
        }

        if (!mongoose.Types.ObjectId.isValid(id)) {
            return res.status(400).json({ message: "Invalid ID format" });
        }

        const event = await Event.findById(id);
        if (!event) return res.status(404).json({ message: "Event not found" });
        
        const analytics = {
            ticketsBooked: event.capacity - event.availableTickets,
            revenue: (event.capacity - event.availableTickets) * event.price,
        };
        res.json({ event, analytics });
    } catch (err) {
        res.status(500).json({ message: "Server Error" });
    }
};

exports.updateEvent = async (req, res) => {
    try {
        const { id } = req.params;
       
        if (!mongoose.Types.ObjectId.isValid(id)) {
            return res.status(400).json({ message: "Invalid ID format" });
        }

        // Create a copy of the body data
        const updatedData = { ...req.body };
         delete updatedData.availableTickets;
        // 1. Fix Image Path: Store only the relative path (more flexible for deployment)
        if (req.file) {
            updatedData.image = `/uploads/${req.file.filename}`;
        }

        // 2. Data Cleaning: FormData sends everything as strings. Convert them back!
        if (updatedData.price) updatedData.price = Number(updatedData.price);
        if (updatedData.capacity) {
            updatedData.capacity = Number(updatedData.capacity);
            // Optional: If capacity changes, you might need to adjust availableTickets logic here
        }

        const updatedEvent = await Event.findByIdAndUpdate(
            id, 
            { $set: updatedData }, 
            { new: true, runValidators: true }
        );

        if (!updatedEvent) {
            return res.status(404).json({ message: "Event not found" });
        }

        res.json(updatedEvent);
    } catch (err) {
        console.error("Update Error:", err);
        res.status(500).json({ message: "Update Failed: " + err.message });
    }
};

exports.deleteEvent = async (req, res) => {
    try {
        const { id } = req.params;
        if (!mongoose.Types.ObjectId.isValid(id)) {
            return res.status(400).json({ message: "Invalid ID format" });
        }

        await Event.findByIdAndDelete(id);
        res.json({ message: "Event Deleted Successfully" });
    } catch (err) {
        res.status(500).json({ message: "Delete Failed" });
    }
};
exports.getUniqueCities = async (req, res) => {
    try {
        const cities = await Event.distinct('location');
        res.json(cities);
    } catch (err) {
        res.status(500).json({ message: "Error fetching cities" });
    }
};
exports.getFilteredEvents = async (req, res) => {
    try {
        const { keyword, city, category, dateFrom, dateTo, page = 1, limit = 9 } = req.query;
        let query = {};

        if (keyword) query.title = { $regex: keyword, $options: 'i' };
        if (city) query.location = city;
        if (category) query.category = category;
        if (dateFrom || dateTo) {
            query.date = {};
            if (dateFrom) query.date.$gte = new Date(dateFrom);
            if (dateTo) query.date.$lte = new Date(dateTo);
        }

        const skip = (page - 1) * limit;
        const total = await Event.countDocuments(query);
        const events = await Event.find(query).sort({ date: 1 }).skip(skip).limit(Number(limit));

        res.json({
            events,
            totalPages: Math.ceil(total / limit),
            currentPage: Number(page),
            totalEvents: total
        });
    } catch (err) {
        res.status(500).json({ message: "Error filtering events" });
    }
};
exports.getUniqueCategories = async (req, res) => {
    try {
        const categories = await Event.distinct('category');
        res.json(categories);
    } catch (err) {
        res.status(500).json({ message: "Error fetching categories" });
    }
};
exports.getEventDetails = async (req, res) => {
    try {
        const event = await Event.findById(req.params.id);
        if (!event) return res.status(404).json({ message: "Event not found" });

        // Fetch 3 related events from the same category, excluding the current one
        const related = await Event.find({ 
            category: event.category, 
            _id: { $ne: event._id } 
        }).limit(3);

        res.json({ event, related });
    } catch (err) {
        res.status(500).json({ message: "Error fetching event details" });
    }
};